oauth2_proxy:
  build: .
  ports:
    - 4180:4180
nginx:
  image: nginx:1.11.1-alpine
  links:
    - oauth2_proxy
  ports:
    - 8082:80
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
